name = "BScThesis"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LogicAndAutomata"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.25.0-rc2"

[[require]]
name = "AutomataTheory"
git = "https://github.com/ctchou/AutomataTheory.git"
rev = "733ffc2d9a607f249123b7b0e87654166a5740dc"

[[lean_lib]]
name = "LogicAndAutomata"
